### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [SatoNozomi44/Tra_gori#121]
MVPリリースお疲れ様でした、
機能確認を行いました。LGTMです。
全体的に完成度も高く、技術力も一定水準を上回っているように判断しました。
以下の対応を就活準備と並行して進まましょう！

---

■改善点
・独自ドメイン対応
・テストを書きましょう
・Rubocopを通しましょう。（やや1メソッド辺り長い箇所があるように見えました）
```ruby
# 例 app/controllers/gachas_controller.rb
...
def create
  if current_user.number_of_banana.count >= 5
    current_user.number_of_banana.decrement!(:count, 5)

    unacquired_illustrations = Illustration.where.not(id: current_user.illustrations.pluck(:id))
    @illustration = unacquired_illustrations.order("RANDOM()").first

    hoge(@illustration)

  else
    flash[:alert] = t(".shortage_banana")
    render :new, status: :unprocessable_entity
  end
end

private

def hoge(illustration)
  if illustration
    current_user.illustrations << illustration
    redirect_to result_gacha_path(illustration)
  else
    flash[:warning] = t(".all_acquired")
    redirect_to training_records_path
  end
end
```

上記のレビューをタスクに落とし込み、issueに書きましたら、下記URLのように1週間毎に列を作成して、そこにissueを配置していってください。こちらのissueは対応が済みましたらcloseしていただいて大丈夫です。

https://github.com/users/Tsuchiya2/projects/2/views/1

また書き出したissueをもとに修正完了までのスケジュール、本リリースの目処を教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by SatoNozomi44** [comment]
お疲れ様です。
MVPレビュー、ありがとうございました！

上記レビュー内容を元にissueを作成し、Projectに落とし込みましたのでご確認をお願いします。

https://github.com/users/SatoNozomi44/projects/3/views/1
___
修正完了までのスケジュール、本リリースの目安につきましては下記の通りとなります。
- 修正完了（独自ドメイン設定のみ）：1/31 (水)
- 本リリース（機能面・テスト・Lintチェック）：2/18(日)

テスト・Lintチェックにつきましては、本リリース機能を実装後に書く予定でスケジュールの見込みをしていましたので、本リリース目安の方に含ませて貰っています。

**Comment by Tsuchiya2** [comment]
ありがとうございます！
引き続き頑張ってください。
